name: Build
on: [push, pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_Token }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: yarn install
    - name: build
      run: yarn buildLinux

  build_on_mac:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GH_Token }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: npm install
    - name: build
      run: yarn buildMac

  build_on_win:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_Token }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: yarn install
    - name: build
      run: yarn buildWin